### ISSUE TITLE
Add SVG optimisation to gulpfile

### ISSUE THREAD

**Issue by tawashley** [code-computerlove/node-static-site-generator#12]
To run before SVG sprite is generated

**Comment by furzeface** [comment]
Is this one [done](https://github.com/code-computerlove/node-static-site-generator/blob/master/gulpTasks/image-minify.js#L21) @tawashley?

**Comment by tawashley** [comment]
Yeah, the initial work was done. I was looking at ways to optimise individual SVG files before gulp did the spriting, but that can be added as a new issue if needed.
