### ISSUE TITLE
Clean up: Remove 'forked from' label, give the project a proper name

### ISSUE THREAD

**Issue by bmds** [code-computerlove/node-static-site-generator#17]
We should probably rename the project to static-site-generator to avoid confusion and set it up so that it isn't a fork of @andrewbrandwood original one as that is creating issues around pull requests etc.

**Comment by tawashley** [comment]
@bmds @furzeface 

Walkthrough for making a new repo from a forked one - https://help.github.com/articles/duplicating-a-repository/

I agree with the removal of the word 'node'. We could use this time to try and come up with a name for the project. static-site-generator sounds like generic-repository-3251.

Names I've thought are whilst writing this comment (and abit of googling)
- dynamo
- genesis
- conjurer
- awesome project setup 3000 (ok, not that one).

**Comment by bmds** [comment]
Suggestions from the email chain we had for this:

* http://www.thesaurus.com/browse/beginning?s=t (A word form this list)
* Osmosis
* Genesis
* Spark
* Cornerstone
* Square One

**Comment by tawashley** [comment]
@bmds Ha, yes, forgot about this. Think the only rule should be to not use a js suffix.

**Comment by furzeface** [comment]
We're probably going to need to do this safely when no-one's working on the project, then either update all of our remote URLs locally or clone the new repo down before commencing work again, right?

Shall we pick a time to do this, maybe this afternoon before we leave the office?

@andrewbrandwood @bmds @tawashley

**Comment by tawashley** [comment]
@furzeface Agreed with the doing this when no one is working on it, re-clone - as we are basically making a new repo from an existing one.

I had envisioned doing the whole 'give this thing a new repo' and 'give this thing a name' to be one after another.

**Comment by furzeface** [comment]
Yeah for sure. Let's do it later, I'm concerned about keeping all the
history etc too so let's do it right!!

**Comment by tawashley** [comment]
Who is the real repo? Ooooo

https://github.com/code-computerlove/slate
