### ISSUE TITLE
Re-assess when Travis CI runs

### ISSUE THREAD

**Issue by tawashley** [code-computerlove/node-static-site-generator#34]
With the recent activity and to get into the routine of: making a branch, doing the work and the raising a Pull Request along with the fact I usually do small commits (and push after each one  :dizzy_face: ) should Travis CI be set to only build when raising pull requests? At the moment pushing a final change on a branch and then raising a PR resulting in two Travis builds.

I don't think you can stop a merge from happening if the build is red and it would require everyone to be mindful of breaking things etc. This is as minor as things get but I'm curious to hear people's thoughts. 

@andrewbrandwood @bmds  @furzeface

**Comment by furzeface** [comment]
You could whitelist only the master branch to do a full build perhaps?

**Comment by furzeface** [comment]
```yml
branches:
  only:
    - master
```

Perhaps? 

Thing is though, we would still need to test the individual branches anyway I guess so I think it's worth leaving it how it is to be honest.

**Comment by furzeface** [comment]
> At the moment pushing a final change on a branch and then raising a PR resulting in two Travis builds.

To be fair though, you should probably be doing your final push on the branch, waiting for it to pass and _then_ do the PR.

**Comment by tawashley** [comment]
Yeah, ok. Was just wondering. I've had a few times where a build doesn't run for a good while as there are still a few, at that point, stale builds that need running before building using the new improved code.

**Comment by furzeface** [comment]
On a side note, how awesome is _this_!?: https://docs.travis-ci.com/user/customizing-the-build/#Using-regular-expressions

**Comment by furzeface** [comment]
Also _If you don’t want to run a build for a particular commit, because all you are changing is the README for example, add *[ci skip]* to the git commit message._

**Comment by tawashley** [comment]
Give a dev an inch and they'll take a mile - also known as the quick way to skip a built and push up quickly done code

**Comment by furzeface** [comment]
It needs speeding up too :dizzy_face:

**Comment by tawashley** [comment]
What the Travis build does isn't massively complex.

* `npm install` at the root of the project - first pass test to ensure everything installs correctly
* Runs mocha tests
   * This includes a seperate `npm install` before running `mocha`

It's taking a while due to the first npm install. With dependencies such as PhantomJS and imagemin having large binaries contributing to the long duration.

The mocha tests also rely on the first step happening as the `gulpSpec.js` does a run through of the build and release tasks and then testing the output.

I don't want to say wontfix but I can't think of a way of speeding it up myself. All ideas welcome.

**Comment by tawashley** [comment]
I come to realise that travis building on push and pull request is a good thing to have. This ensures tests are run if and when people push directly into master, even though PRs are preferred.

**Comment by furzeface** [comment]
Yup yup go ahead @tawashley all good.

**Comment by tawashley** [comment]
Closing as per discussion
