### ISSUE TITLE
Running gulp serve when setting the project up (first time) causes missing modules 

### ISSUE THREAD

**Issue by code-mattclaffey** [code-computerlove/node-static-site-generator#36]
I pulled the project down and I ran **npm install**, **gulp** and then **gulp serve** and it says I am missing these modules: 

**cannot find module js**
**cannot find module ico**

**Comment by tawashley** [comment]
I've seen this once or twice, had a look a thought I'd caught it. 

You're able to access the site alright, it's the express node complaining?

**Comment by code-mattclaffey** [comment]
@tawashley the site still runs but when I look into the console it cannot find critical-bundle.js and favicon.ico so I am assuming that its something to do with the fact that it cant find them so it throws the error?

**Comment by tawashley** [comment]
Hmm, ok. Is this on Mac? 
Also, what version of node are you on
node --version
npm --version

**Comment by code-mattclaffey** [comment]
Machine - Mac
Node version -  4.1.0 
NPM -  3.3.3

**Comment by tawashley** [comment]
Thanks. I'll have a look.

**Comment by tawashley** [comment]
https://github.com/code-computerlove/node-static-site-generator/pull/37 Pull Request fixes this. Closing.
