### ISSUE TITLE
Duplicated mixin

### ISSUE THREAD

**Issue by furzeface** [code-computerlove/node-static-site-generator#42]
Matt and I noticed that the `@mixin font-size` is in [two](https://github.com/code-computerlove/node-static-site-generator/blob/master/_source/styles/_tools/_tools.typography.scss) [places](https://github.com/code-computerlove/node-static-site-generator/blob/master/_source/styles/_tools/_tools.mixins.scss#L94). 

I didn't want to remove one without asking first, so which is the appropriate place to have it? 
Perhaps keep the one in `typography.scss` and move `@mixin font` into it too? I'll do this now if you agree?

@tawashley @andrewbrandwood @bmds

**Comment by andrewbrandwood** [comment]
Better in one place and i'd agree typography is ideally where it should be.

**Comment by tawashley** [comment]
@furzeface Is this ongoing or has the work been completed, pulled in?

**Comment by furzeface** [comment]
Yeah this work has been done, I did leave the branch open for a bit more Sass refactoring but go ahead and merge it and I will just pick up more little bits as I go, thanks :+1:
