### ISSUE TITLE
Add gulp task to make a new component

### ISSUE THREAD

**Issue by tawashley** [code-computerlove/node-static-site-generator#46]
Whilst it may prove quicker for devs to make a partial and the files that go with it directly, it could prove helpful to have a gulp task that automates this. 

I'm thinking something such as:

`gulp component ComponentName`

This would then create:

* a folder inside of _partials called `ComponentName`
    * `ComponentName.hbs`
    * `ComponentName.scss` - with a comment at the top to make sure it's detected by sass generate contents
* Run gulp (or the individual tasks needed).

Run this and spend time developing the component, not creating the file

@iamtomnewton Would this be something that helps or just something to get in the way?

**Comment by tawashley** [comment]
https://github.com/code-computerlove/node-static-site-generator/pull/47

**Comment by tawashley** [comment]
https://github.com/code-computerlove/node-static-site-generator/pull/47 has now been pulled in. Closing.

**Comment by iamtomnewton** [comment]
Missed this one, would be really handy. Quite annoying having to create files and folders, good idea!

**Comment by tawashley** [comment]
Well your wish is my command - BAM done. https://github.com/code-computerlove/node-static-site-generator/blob/master/docs/welcome.md#adding-a-new-component
