### ISSUE TITLE
Allow express deeper URLs

### ISSUE THREAD

**Issue by tawashley** [code-computerlove/node-static-site-generator#9]
At the moment, working locally and hitting a deep URL e.g. /foo/bar, even with a view file an error would occur. The routes (currently styleguide.js) file will need to be changed to allow deeper URLs (currently only scoped to one-level URLs)

**Comment by andrewbrandwood** [comment]
In the routes of styleguide change the get routing to

website.get(['/*','/:loc'], controller.get);

notice the * after the /

I'll update when I get 5 mins

**Comment by tawashley** [comment]
As per Branny's above comment, this change has been made and merged in.
